### ISSUE TITLE
Single-project MSIX doesn't support producing a MSIX Bundle

### ISSUE THREAD

**Issue by andrewleader** [microsoft/WindowsAppSDK#1808]
### Describe the bug

Despite selecting "Generate app bundle = Always" in the UI, a .msixbundle file is not generated. The root cause is that single-project MSIX doesn't support generating MSIX Bundles today, however that manifests as a bug to the developer since the UI allows you to select an option that doesn't work.

![image](https://user-images.githubusercontent.com/13246069/142085992-56116f14-2707-4d3a-9985-5ad057af52c1.png)

### Steps to reproduce the bug

1. Create a new app
2. Use the Package & Publish UI to start creating a package
3. Select "Generate app bundle = Always" and select two build combinations
4. Attempt to build the package
5. Notice a silent error occurs

```
Microsoft.Build.Msix.Packaging.targets(341,5): error MSB6011: Invalid parameters passed to the Microsoft.Build.Msix.Symbols.WinAppSdkCheckFastlinkPdb task.
```

6. Notice that no bundle is created, only separate MSIX's

### Expected behavior

A bundle should be created.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### IDE

Visual Studio 2022-preview

**Comment by JanRajnoha** [comment]
What is the status of issue?

**Comment by JanRajnoha** [comment]
Is any workaround for creating msixbundle? @andrewleader

**Comment by koenvd** [comment]
Any update on this one @andrewleader ? Or possible workaround ...

**Comment by JPTGamesAndApps** [comment]
Manual workaround for those in need: 
* Create folders Parent and Parent\Package.
* Copy the .msix files to Package folder. 
* Execute the command below. Update the path as relevant.
* Will produce the .msixbundle in the Parent folder.

"C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\MakeAppx.exe" bundle /d "C:\...\Parent\Package" /p "C:\...\Parent\AppName_Bundle.msixbundle"

**Comment by JanRajnoha** [comment]
Any update @evelynwu-msft ?

**Comment by evelynwu-msft** [comment]
Unfortunately support for this won't be part of the 1.2 release.

**Comment by erikvanappeldoorn** [comment]
Would love to see support for .msixbundles in VS 2022. It is currently blocking me from upgrading an existing UWP Microsoft Store app to WinUI3

**Comment by mattleibow** [comment]
Been hacking away at this and I think I got something that will make this all work wonderfully:

https://gist.github.com/mattleibow/8332ed79b569c9d7bbdae64a6e8142a6

If we get some testing on this we may be able to include somewhere until the WASDK issue is resolved.

**Comment by zhuxb711** [comment]
My Github Action for misxbundle, hope that will help somebody. This will produce exactly same files as Uwp application

```yml
    env:
      AppxBundle: Always
      AppxPackageBuildMode: SideloadOnly
      Configuration: Release
      ProjectName: <Your Project Name>
      CertThumbprint: <Your Thumbprint>
      SolutionPath: ${{github.workspace}}\<Your_Solution_Name>.sln
      CertificationPath: ${{github.workspace}}\<Your_Certification_Name>.pfx
      X64OutputPath: ${{github.workspace}}\Output\x64\
      ARM64OutputPath: ${{github.workspace}}\Output\arm64\
      BundleOutputPath: ${{github.workspace}}\Output\Bundle
      AppMainfestPath: ${{github.workspace}}\<Your_Solution_Name>\Package.appxmanifest

    steps:
      - name: Get current version
        id: versionStep
        run: |
          $xml = [XML](Get-Content $env:AppMainfestPath)
          $version = $xml.Package.Identity.Version
          echo "Version=$version" >> $env:GITHUB_OUTPUT

      - name: Decode the SignCert
        run: |
          $pfxBase64 = [System.Convert]::FromBase64String("${{secrets.SIGNCERT}}")
          [IO.File]::WriteAllBytes("$env:CertificationPath", $pfxBase64)

      - name: Create the X64 msix pacakge
        run: msbuild $env:SolutionPath /nologo /nr:false /t:Clean /p:Configuration=$env:Configuration /t:$env:ProjectName:Rebuild /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:AppxPackageBuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:CertificationPath /p:PackageCertificatePassword=${{secrets.SIGNCERTPASSWORD}} /p:PackageCertificateThumbprint=$env:CertThumbprint /p:AppxPackageDir=$env:X64OutputPath /p:GenerateAppxPackageOnBuild=true
        env:
          Platform: x64

      - name: Create the ARM64 msix pacakge
        run: msbuild $env:SolutionPath /nologo /nr:false /t:Clean /p:Configuration=$env:Configuration /t:$env:ProjectName:Rebuild /p:Platform=$env:Platform /p:UapAppxPackageBuildMode=$env:AppxPackageBuildMode /p:AppxBundle=$env:AppxBundle /p:PackageCertificateKeyFile=$env:CertificationPath /p:PackageCertificatePassword=${{secrets.SIGNCERTPASSWORD}} /p:PackageCertificateThumbprint=$env:CertThumbprint /p:AppxPackageDir=$env:ARM64OutputPath /p:GenerateAppxPackageOnBuild=true
        env:
          Platform: arm64

      - name: Generate the msixbundle folder with all the msix files
        run: |
          New-Item -Path $env:BundleOutputPath -ItemType Directory -Force

          $x64MsixFiles = Get-ChildItem -Path $env:X64OutputPath -Recurse -Include *.msix
          $arm64MsixFiles = Get-ChildItem -Path $env:ARM64OutputPath -Recurse -Include *.msix

          $x64MsixFiles | ForEach-Object {
              Copy-Item -Path $_ -Destination $env:BundleOutputPath
          }

          $arm64MsixFiles | ForEach-Object {
              Copy-Item -Path $_ -Destination $env:BundleOutputPath
          }

      - name: MSIX Bundler
        uses: LanceMcCarthy/Action-MsixBundler@v1.0.1
        with:
          msix-folder: ${{env.BundleOutputPath}}
          msixbundle-filepath: ${{env.BundleOutputPath}}\Your_App_Name_${{steps.versionStep.outputs.Version}}_x64_arm64.msixbundle
          msixbundle-version: ${{steps.versionStep.outputs.Version}}
          sdk-version: 10.0.22621.0
          architecture: x64
          enable-bundle-signing: true
          certificate-path: ${{env.CertificationPath}}
          certificate-private-key: ${{secrets.SIGNCERTPASSWORD}}
          signing-hash-algorithm: SHA256

      - name: Cleanup redundant and secret files
        run: |
          Remove-Item -Path $env:CertificationPath

          $msixFiles = Get-ChildItem -Path $env:BundleOutputPath -Recurse -Exclude *.msixbundle
          $msixFiles | ForEach-Object {
              Remove-Item -Path $_
          }

      - name: Copy optional files
        run: |
          $optionalFiles = Get-ChildItem -Path $env:X64OutputPath -Recurse -Include *.cer,*.ps1,*.msixsym
          $optionalFiles | ForEach-Object {
              Copy-Item -Path $_ -Destination $env:BundleOutputPath
          }

          $resourceDirectory = Get-ChildItem -Path $env:X64OutputPath -Directory -Recurse -Include Add-AppDevPackage.resources
          $resourceDirectory | ForEach-Object {
              Copy-Item -Recurse -Path $_ -Destination $env:BundleOutputPath
          }

          $oldCertName = (Get-Item -Path "$env:BundleOutputPath\*.cer").Name
          $newCertName = $oldCertName.Replace("x64","x64_arm64")
          Rename-Item -Path "$env:BundleOutputPath\$oldCertName" -NewName $newCertName

          $arm64symfiles = Get-ChildItem -Path $env:ARM64OutputPath -Recurse -Include *.msixsym
          $arm64symfiles | ForEach-Object {
            Copy-Item -Path $_ -Destination $env:BundleOutputPath
          }

      - name: Upload MSIXBUNDLE package
        uses: actions/upload-artifact@v3.1.2
        with:
          name: MSIXBUNDLE Package
          path: ${{env.BundleOutputPath}}
```
