### ISSUE TITLE
The 1.4.230518007-experimental1 installer is flaky

### ISSUE THREAD

**Issue by tristanlabelle** [microsoft/WindowsAppSDK#3760]
### Describe the bug

We install WindowsAppSDK `1.4.230518007-experimental1` in CI and it has started failing randomly after working for several weeks:

```
Installing license: MSIX_MAINPACKAGE_LICENSE
Install License result : 0x0 
Installing license: MSIX_SINGLETONPACKAGE_LICENSE
Install License result : 0x0 
Deploying package: Microsoft.WindowsAppRuntime.1.4-experimental1_4000.868.150.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0 
Deploying package: Microsoft.WindowsAppRuntime.1.4-experimental1_4000.868.150.0_x86__8wekyb3d8bbwe
Package deployment result : 0x0 
Deploying package: MicrosoftCorporationII.WinAppRuntime.Main.1.4-e1_4000.868.150.0_x64__8wekyb3d8bbwe
Package deployment result : 0x0 
Error: Process completed with exit code 1.
```

### Steps to reproduce the bug

Our CI uses a `windows-2022` GitHub runner with this step:

```yaml
    - name: Install WindowsAppRuntime 1.4
      shell: pwsh
      run: |
        $installer = "$env:TEMP\installer.exe"
        invoke-WebRequest -Uri https://aka.ms/windowsappsdk/1.4/1.4.230518007-experimental1/windowsappruntimeinstall-x64.exe -Outfile $Installer
        & $installer
```

### Expected behavior

The installer should reliably succeed, or at least provide error information when it fails.

### Screenshots

History of successes vs failures:
![image](https://github.com/microsoft/WindowsAppSDK/assets/2314287/03fd4b4e-15f2-4b89-a30e-aff77e54a312)

### NuGet package version

Windows App SDK 1.4 Experimental 1: 1.4.230518007-experimental1

### Packaging type

Unpackaged

### Additional context

Windows version: `windows-2022` github runner, see: https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
We tried capturing an ETL trace but it seems like the process is ending unexpectedly and the trace doesn't contain any useful information.
